### PR TITLE
request.js: oauth 1 response query string

### PR DESCRIPTION
**Pull request by rmonnier9**

### CODE REVIEW

**Comment by simov** [comment]
Thanks, however, I'm still not convinced that this works as expected.

Can you run your server using this:

```bash
npm i --save-dev request-logs
DEBUG=req,res,json node app.js
```

This will print the request/response information for the `request_url`. Can you copy/paste the entire output here?

**Comment by rmonnier9** [comment]
Here it is:
`
req POST https://apifeed.sellsy.com/0/request_token
    user-agent:    simov/grant/5.4.13
    Authorization: OAuth oauth_callback="http%3A%2F%2Flocalhost%3A1337%2Fconnect%2Fsellsy%2Fcallback",oauth_consumer_key="9306ccbdb9ce65b2ad734bc13c1e126137cf3f27",oauth_nonce="26a88655cf4149c9bbd2e890fe213309",oauth_signature_method="HMAC-SHA1",oauth_timestamp="1624169590",oauth_version="1.0",oauth_signature="%2F%2FzumLK%2FEEhYm0I3F%2BMf%2F931YBw%3D"
    Host:          apifeed.sellsy.com
(node:63159) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headerNames is deprecated
(Use `node --trace-deprecation ...` to show where the warning was created)
res 200 OK
    server:            nginx
    date:              Sun, 20 Jun 2021 06:13:52 GMT
    content-type:      application/json; encoding=utf-8
    transfer-encoding: chunked
    connection:        close
json
    authentification_url=https://apifeed.sellsy.com/0/login.php&oauth_token=79b9ea9386eb00b060675293b32cd0ae18a1e4ab&oauth_token_secret=5f6dbf159ce92cba30dcf185a457346c8f8e5f96&oauth_callback_confirmed=true
[2021-06-20T06:13:10.915Z] debug GET /connect/sellsy (523 ms) 302
`

and then:

`
req POST https://apifeed.sellsy.com/0/oauth/access_token
    user-agent:    simov/grant/5.4.13
    Authorization: OAuth oauth_consumer_key="9306ccbdb9ce65b2ad734bc13c1e126137cf3f27",oauth_nonce="5f478742f7494ab58d71996831879963",oauth_signature_method="HMAC-SHA1",oauth_timestamp="1624169637",oauth_token="79b9ea9386eb00b060675293b32cd0ae18a1e4ab",oauth_verifier="5fe255de5d933fadf79f0ba8f7626ff3b8db1f4e",oauth_version="1.0",oauth_signature="LIcKzcjSfQnqf6CpWuyj4mKTyps%3D"
    Host:          apifeed.sellsy.com
res 200 OK
    server:            nginx
    date:              Sun, 20 Jun 2021 06:14:38 GMT
    content-type:      text/plain; encoding=utf-8;charset=UTF-8
    transfer-encoding: chunked
    connection:        close
[2021-06-20T06:13:57.285Z] debug GET /connect/sellsy/callback?&oauth_token=79b9ea9386eb00b060675293b32cd0ae18a1e4ab&oauth_verifier=5fe255de5d933fadf79f0ba8f7626ff3b8db1f4e (187 ms) 302

`

**Comment by simov** [comment]
Wait, you have to use `DEBUG=req,res,body node app.js` instead, because it's not a JSON response body. Can you do that and update your comment?

**Comment by rmonnier9** [comment]
I confirm that it works, I'm then able to consume the api with the provided tokens.

**Comment by simov** [comment]
Ok, now I understand why the `output` a string. It's because they return the body with `content-type: application/json` where that clearly is not a valid JSON body.

**Comment by rmonnier9** [comment]
Oh interesting fact. I try to send them a message on their support.
Do you think we should create an if case for sellsy?

**Comment by simov** [comment]
@rmonnier9 the fix should be here instead:

```diff
diff --git a/lib/flow/oauth1.js b/lib/flow/oauth1.js
index 8ec2584..5654818 100644
--- a/lib/flow/oauth1.js
+++ b/lib/flow/oauth1.js
@@ -40,6 +40,9 @@ exports.request = ({request:client}) => async ({provider, input}) => {
   }
   try {
     var {body:output} = await request({...client, ...options})
+    if (provider.sellsy) {
+      output = qs.parse(output)
+    }
   }
   catch (err) {
     var output = {error: err.body || err.message}
```

It's inside lib/flow/oauth1.js at the end of the first method immediately after the HTTP request.

If you can do that instead of your current fix, I will add tests and release the patch later today.

**Comment by rmonnier9** [comment]
Thanks, this is done.

**Comment by simov** [comment]
Support for `sellsy` was published in v5.4.15, here is the [test](https://github.com/simov/grant/commit/d7684aa3202192049a74e2ae9492d601a839a4f1) for it if you are curious to know :+1:

**Comment by rmonnier9** [comment]
Thanks a lot and awesome work.

I use Strapi that has integrated grant, would bé happy to help in the future in thid project !
Oauth is a pain 😄

**Pull request merged**
