### PR TITLE
Add atlassian

### PR DESCRIPTION
**Pull request by ohjames**
1. Add atlassian (tested it and it's working)
2. Split provider list with newlines in README so that provider changes don't raise a huge git log and so it's easier to poke your provider in there (a single newline is changed to a space in a markdown file anyway... you need two newlines in a row to get a break).

### CODE REVIEW

**Comment by ohjames** [comment]
You can verify the list of providers still looks the same here: https://github.com/ohjames/grant

**Comment by simov** [comment]
Picked your commit about the config, but not the other one. I'm actually generating that line using a script, that is not part of this repository. Also I like those links being on a single line, because that makes the README more manageable for me, I have word-wrap enabled in my editor, and that way it takes much less space.

:+1:

**Comment by ohjames** [comment]
@simov  The git commit will still be one giant huge single line change instead of a simple manageable change of a few lines, so having it all on one line like that is also bloating your git commit history and making the git diffs unreadable.

**Comment by simov** [comment]
I'm generating that line and almost never look at the diffs for it. Let me show you how it looks like in my editor as well:

grant-providers

as you can see it takes just one screen, so I can quickly scroll pass through it.

That being said I understand how this can be awkward for other people to update that line, depending on their setup. But I'm always re-generating it anyway because I keep another JSON file with all of the documentation URLs in it.

**Comment by ohjames** [comment]
Sure it looks one way, but in terms of git, it's a multi-kilobyte change on each update instead of a multi-byte change.

**Pull request closed without merging**
