### PR TITLE
Add support for fitbit OAuth2 flow.

### PR DESCRIPTION
**Pull request by brogowski**
Support for fitbit OAuth2 flow.

### CODE REVIEW

**Comment by simov** [comment]
I merged your first commit and made a [few improvements](https://github.com/simov/grant/commit/592720d305a1a593b1bc99cf7c1be93924e16c7b) on top of it.

Basically you don't need custom parameter for the `client_id`, because that's the default key to use with OAuth2. I also fixed your test to be closer to the `reddit` one. Knowing that the `authorization` header have been sent is enough, the right format is tested in the underlying module that Grant uses - Request.

:+1:

**Comment by brogowski** [comment]
Thanks for merge, and sorry for late response.

Unfortunately your changes will not work for fitbit2.
I already tried reddit implementation in the first place but fitbit2 is little different.

Fitbit2 have 3 authorization parts (client key, client secret and client id).
In reddit case, key and secret are going to auth header and are removed from form. In fitbit2 case, client id and secret are going to auth header and in form you still have to put key and secret.

That is a reason why my test was checking authorization header – I wanted to be sure that it contains both client id and client secret.

**Comment by simov** [comment]
Just pull master and test with it. See [here](https://github.com/simov/grant#alternative-require) on how to require the module in your app. It works on my end.

I'm going to publish the new release by the end of this week. Let me know if it doesn't work for you after testing.

**Comment by brogowski** [comment]
I have tested it but it's not working.

Response:

```{ "error": { "errors": [ { "errorType": "invalid_client", "message": "Invalid authorization header. Client id invalid. Visit https://dev.fitbit.com/docs/oauth2 for more information on the Fitbit Web API authorization process." } ], "success": "false" } }```

**Comment by simov** [comment]
credentials

You have to set the `key` and `secret` in your configuration to use the OAuth2 credentials. You are most probably using the old OAuth1 Client Key - this is what the error says. Then you have to include all of the OAuth scopes listed in the docs:

```js
"fitbit2": {
  "key": "Client ID",
  "secret": "Client Secret",
  "scope": [
    "activity",
    "heartrate",
    "location",
    "nutrition",
    "profile",
    "settings",
    "sleep",
    "social",
    "weight"
  ]
}
```

**Comment by brogowski** [comment]
Ok I got it - it's working now. You were right - Client ID should go to key property. I thought that its required to send all 3 values.

Sorry for problem and confusion.

**Comment by simov** [comment]
Just published version [3.5.2](https://github.com/simov/grant/blob/master/CHANGELOG.md)

**Pull request closed without merging**
