### PR TITLE
Fixing errors in Typings

### PR DESCRIPTION
**Pull request by tvvignesh**
Just minor fixes to fix the issues as mentioned here: https://github.com/simov/grant/issues/203#issuecomment-728151983

### CODE REVIEW

**Comment by tvvignesh** [comment]
Closing this PR. This might not be a valid fix.

**Comment by tvvignesh** [comment]
Currently I changed the typings to look like this: https://gist.github.com/tvvignesh/cc4c5be41c3a9d6a08d4df4b04c32f09 and it works for me.

**Comment by simov** [comment]
The problem is that `defaults` is not required. While it will be defined in 99% of the cases, by design it is not strictly required. But I'll definitely take a look. I didn't had the time to compile anything so I relied solely on the what VSCode was telling me.

**Comment by simov** [comment]
Can you share your tsconfig as I'm really not getting that second error?

**Comment by simov** [comment]
Published the missing comma fix in v5.4.7

**Comment by tvvignesh** [comment]
@simov This is how it looks like:

```json
{
  "compileOnSave": true,
  "compilerOptions": {
    "target": "ES2017",
    "module": "commonjs",
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": "node",
    "skipLibCheck": true,
    "noImplicitAny": false,
    "noUnusedLocals": true,
    "removeComments": true,
    "preserveConstEnums": true,
    "allowSyntheticDefaultImports": true,
    "outDir": "dist",
    "rootDir": "src",
    "declarationMap": true,
    "sourceMap": true,
    "strict": true,
    "noEmitOnError": true,
    "lib": ["ES2017", "esnext.asynciterable", "dom"]
  },
  "include": ["./src/**/*"],
  "exclude": ["node_modules", "**/*.spec.ts", "**/*.d.ts"]
}
```

I guess you might not have strict set to true if I am not wrong.

**Comment by urossmolnik** [comment]
@simov can `grant-koa` be published too? It has a exact dependency on grant 5.4.6 and types are a problem there.

**Comment by simov** [comment]
Good call, I can't remember why I pinned the version there, I'll publish it in a few hours as it's a bit late over here :+1:

**Comment by simov** [comment]
Published, also set the dependency to use `^`

**Pull request closed without merging**
