### PR TITLE
add phantauth support

### PR DESCRIPTION
**Pull request by szkiba**
PhantAuth was designed to simplify testing of applications using OpenID Connect authentication by making use of randomly generated users.

By using PhantAuth, you can test applications built on Grant with an unlimited number of test users. It could bring the developers of applications using Grant considerable added value.

To learn more, please visit: https://www.phantauth.net

### CODE REVIEW

**Comment by simov** [comment]
Thanks :+1:

**Comment by szkiba** [comment]
Thank you for merging :)
It would be nice if you could add phantauth to your sample/playground app...

After developing PhantAuth service I'm working now on how to reach as many developers and testers as possible.
Any sort of help would be greatly appreciated: blog post, tweet, review, etc.

**Comment by simov** [comment]
It's already been added to my playground app, but it's not deployed yet, until I publish the next release.

I had a look at your service, it definitely looks interesting, hopefully I'll have the time to play around with it a bit more in future.

**Comment by szkiba** [comment]
Thank you!

**Pull request merged**
