### PR TITLE
Add Authentiq

### PR DESCRIPTION
**Pull request by ziogaschr**
This PR adds [Authentiq](https://www.authentiq.com/developers/) passwordless authentication.

### CODE REVIEW

**Comment by simov** [comment]
Thanks @ziogaschr !

Isn't the `authorize_url` supposed to be `https://connect.authentiq.io/authorize` as shown [here](https://developers.authentiq.com/api-provider/#authorize)?

Also I noticed a few more custom parameters.

**Comment by ziogaschr** [comment]
Thanks for examining our docs so far @simov, that's great. 

About the endpoint, both are supported. Recently we introduced the one I committed which we try to use more, thanks for finding that we missed to update it in the docs. Though we will keep support for both. You can also check [here](https://connect.authentiq.io/.well-known/openid-configuration).

About the custom parameters, I wasn't sure which ones you handle internally. Shall I add them all?

**Comment by simov** [comment]
Thanks again @ziogaschr ! The `custom_parameters` key is optional. Alternatively you can always  specify them with the `custom_params` key ([docs](https://github.com/simov/grant#custom-parameters))

**Comment by ziogaschr** [comment]
Thanks a lot @simov for the explanation and for merging it. 👍

**Pull request merged**
