### PR TITLE
Handlers/curveball

### PR DESCRIPTION
**Pull request by Nicholaiii**
This PR adds a handler for the framework [Curveball](https://github.com/curveball/core)

### CODE REVIEW

**Comment by simov** [comment]
Amazing! Never heard of it. Is that the Koa2 handler or there is something else added to it?

**Comment by Nicholaiii** [comment]
I really enjoy it for writing services in TypeScript.
It's very close to the Koa 2 implementation, yes. There are a few changes, but mostly just property accessor and switching from ctx.throw to plain throw.

**Comment by simov** [comment]
Got it, I'll take a look at it over the weekend.

**Comment by simov** [comment]
Published in v5.4.5

**Pull request merged**
